### ISSUE TITLE
``nstar`` should not modify its inputs

### ISSUE THREAD

**Issue by bsipocz** [mirca/ze-gsoc16-photutils#2]
@mirca - I'm not sure this is the best way to do this detective reporting, so if you prefer we can move it to gitter or slack or e-mail, etc. It's your call.

So, I've figured out the problem with the aperture plotting. The reference here is this version of the nb: https://github.com/mirca/ze-gsoc16-photutils/blob/4a1f1eb2e16355e46b68e873af37874dc72c3ed4/nstar_example.ipynb

Compared to the first commit of the file, in cell 6, you've changed the order of the plotted things, and the list ``groups`` got emptied out. Moving the ``for`` loop for the aperture plotting to the top of the cell would make it work again.

However, I think it's a bug, as a function (``nstar`` in our case) should not in place modify its input objects but should use copies of it if needed.

**Comment by mirca** [comment]
@bsipocz Thanks!
